apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-watcher
  namespace: developers
  labels:
    team: kafka
spec:
  selector:
    matchLabels:
      metrics: kafka
  endpoints:
  - port: prometheus
