apiVersion: v1
kind: Service
metadata:
  name: kafka-watcher
  namespace: developers
spec:
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: prometheus 
  selector:
    prometheus: kafka-watcher
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
