apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kafka-watcher
  namespace: developers
spec:
  serviceAccountName: default
  serviceMonitorSelector:
    matchLabels:
      team: kafka
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
