apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: data-kafka-zookeeper-0

  namespace: developers 
  labels:
    app: kafka
    release: kafka

spec:

  accessModes:

  - ReadWriteOnce

  resources:

    requests:

      storage: 40Gi

  storageClassName: standard 
