apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: datadir-kafka-0

  namespace: developers 

  labels:
    app: kafka
    release: kafka

spec:

  accessModes:

  - ReadWriteOnce

  resources:

    requests:

      storage: 40Gi

  storageClassName: standard 
