apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  namespace: developers
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Shared
