apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: developers
  labels:
    metrics: kafka
spec:
  selector:
    app: prometheus-kafka-exporter
    release: kafka-exporter 
  ports:
  - protocol: TCP
    port: 5556
    name: prometheus
    targetPort: 5556
