  
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: developers
  labels:
    metrics: kafka
spec:
  selector:
    app: kafka
    release: kafka 
  ports:
  - protocol: TCP
    port: 9308
    name: prometheus
    targetPort: 9308
