apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: tomcat-watcher
  namespace: developers
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
       app: tomcat-web
       type: java
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
