apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: developers
  labels:
    app: tomcat-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8088
    targetPort: 8088
    name: prom
  selector:
    app: tomcat-service
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-web
  namespace: developers
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat-web
        type: java
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8088'
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_AGENT_PORT
          value: "8088"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1"
          limits:
            memory: "1024Mi"
            cpu: "1"
